10 PRINT "Please input your musical alphabet"
20 INPUT a$
30 IF a$ = "C" THEN PRINT "C - D - E - F - G - A - B - C"
40 IF a$ = "D" THEN PRINT "D - E - F? - G - A - B - C? - D"
50 IF a$ = "E" THEN PRINT "E - F? - G? - A - B - C? - D? - E"
60 IF a$ = "F" THEN PRINT "F - G - A - Bb - C - D - E - F"
70 IF a$ = "G" THEN PRINT "G - A - B - C - D - E - F? - G"
80 IF a$ = "A" THEN PRINT "A - B - C? - D - E - F? - G? - A"
90 IF a$ = "B" THEN PRINT "B - C? - D? - E - F? - G? - A? - B"
100 IF a$ = "C#" THEN PRINT "C? - D? - E? - F? - G? - A? - B? - C?"
110 IF a$ = "D#" THEN PRINT "D? - E? - Fx - G? - A? - B? - Cx - D?"
120 IF a$ = "E#" THEN PRINT "E? - Fx - Gx - A? - B? - Cx - Dx - E?"
130 IF a$ = "F#" THEN PRINT "F? - G? - A? - B - C? - D? - E? - F?"
140 IF a$ = "G#" THEN PRINT "G? - A? - B? - C? - D? - E? - Fx - G?"
150 IF a$ = "A#" THEN PRINT "A? - B? - Cx - D? - E? - Fx - Gx - A?"
160 IF a$ = "B#" THEN PRINT "B? - Cx - Dx - E? - Fx - Gx - Ax - B?"
170 IF a$ = "Cb" THEN PRINT "Cb - Db - Eb - Fb - Gb - Ab - Bb - Cb"
180 IF a$ = "Db" THEN PRINT "Db - Eb - F - Gb - Ab - Bb - C - Db"
190 IF a$ = "Eb" THEN PRINT "Eb - F - G - Ab - Bb - C - D - Eb"
200 IF a$ = "Fb" THEN PRINT "Fb - Gb - Ab - Bbb - Cb - Db - Eb - Fb"
210 IF a$ = "Gb" THEN PRINT "Gb - Ab - Bb - Cb - Db - Eb - F - Gb"
220 IF a$ = "Ab" THEN PRINT "Ab - Bb - C - Db - Eb - F - G - Ab"
230 IF a$ = "Bb" THEN PRINT "Bb - C - D - Eb - F - G - A - Bb"

